# Generated by Django 4.0.6 on 2022-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=100)),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailer')),
            ],
        ),
    ]
